name: Automatic release

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!(startsWith(github.ref_name,'renovate/'))"
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: git config
        run: |
          git config --global user.email "hdl-service@hdwlab.co.jp"
          git config --global user.name "hdl-service"
      # WARNING: This may lead commiting .npmrc with token in it (add .npmrc to .gitignore before uncommentint the following block)
      # https://github.com/release-it/release-it/blob/14.14.3/docs/ci.md#npm
      - name: npm config
        env:
          NPM_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          npm config set //npm.pkg.github.com/:_authToken $NPM_TOKEN
          npm config set @dataware-tools:registry=https://npm.pkg.github.com
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      - run: npm run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
