name: Automatic release

on:
  push:
    branches:
      - master
      - fix/auto-release-ci-forked-watanabe # FIXME

jobs:
  publish:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    permissions:
      contents: read
      packages: write
      id-token: read
      pull-requests: read
      actions: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: git config
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
