name: Build test image and test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Install deps
        run: npm install --unsafe-perm
        env:
          NODE_AUTH_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}

      - name: Test
        run: npm run test
