name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"

      - name: Install deps
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Test
        run: npm run test
