name: Test applications

on: [push]

#on:
#  pull_request:
#    branches:
#      - main
#      - master

jobs:
  test-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    strategy:
      matrix:
        node-version: [16.10.0]
        app:
          - app-data-browser-next
#          - app-user-manager
#          - app-launcher

    steps:
      - uses: actions/checkout@v2
        with:
          path: app-common
          submodules: recursive

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install deps of app-common
        working-directory: app-common
        run: npm install --unsafe-perm
        env:
          NODE_AUTH_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}

      - name: Build app-common
        working-directory: app-common
        run: npm run build && rm -r node_modules

      - uses: actions/checkout@v2
        with:
          repository: dataware-tools/${{ matrix.app }}
          path: app
          submodules: recursive

      - name: Build app
        env:
          NPM_REGISTRY: https://npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        shell: bash
        working-directory: app
        run: |
          export DOCKER_BUILDKIT=1
          echo "//${NPM_REGISTRY##*://}/:_authToken=${NPM_TOKEN}" > /tmp/.npmrc
          docker build -t app:latest --ssh default --secret id=npmrc,src=/tmp/.npmrc --target test .

      - name: Test app
        shell: bash
        run: |
          docker run --rm \
            -v ${PWD}/app-common:/app-common:rw \
            app:latest bash -c \
            "rm -r node_modules/@dataware-tools/app-common && ln -s /app-common node_modules/@dataware-tools/app-common && npm run test"

